import { generateClient } from 'aws-amplify/api';
import { post } from 'aws-amplify/api';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - GraphQL queries are generated as JS files
import { getInvite, listInvites } from '../graphql/queries.js';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - GraphQL mutations are generated as JS files
import { updateInvite as updateInviteMutation, deleteInvite as deleteInviteMutation } from '../graphql/mutations.js';

import { InviteModel, type InviteData } from './adt';
import { 
  type GraphQLClient, 
  type GraphQLResponse 
} from '../types/shared';

// Create GraphQL client lazily
let client: GraphQLClient | null = null;
const getClient = (): GraphQLClient => {
  if (!client) {
    client = generateClient() as GraphQLClient;
  }
  return client;
};

// For testing: reset the client
export const __resetClient = () => {
  client = null;
};

export interface CreateInviteData {
  email: string;
  permissionLevel: 'viewer' | 'editor';
  transcriptionId: string;
  transcriptionTitle: string;
  invitedBy: string;
  invitedByFriendly: string;
}

export interface UpdateInviteData {
  id: string;
  status?: string;
  permissionLevel?: 'viewer' | 'editor';
  _version: number;
}

interface GetInviteResponse {
  getInvite: InviteData;
}

interface ListInvitesResponse {
  listInvites: {
    items: InviteData[];
    nextToken?: string;
  };
}

interface UpdateInviteResponse {
  data: {
    updateInvite: InviteData;
  };
}

interface DeleteInviteResponse {
  data: {
    deleteInvite: InviteData;
  };
}

/**
 * Loads all invites for a specific transcription
 * 
 * NOTE: This should ideally use an 'invitesByTranscription' index query 
 * (generated from @index(name: "ByTranscription", queryField: "invitesByTranscription"))
 * but that query is not being generated by Amplify. Using listInvites with 
 * filter as a workaround, consistent with regionService.ts approach.
 * 
 * @param transcriptionId The ID of the transcription
 * @returns Array of InviteModel instances
 */
export const loadInvitesForTranscription = async (transcriptionId: string): Promise<InviteModel[]> => {
  try {
    console.log(`🔍 Loading invites for transcription: ${transcriptionId}`);
    
    const response = await getClient().graphql({
      query: listInvites,
      variables: {
        filter: {
          transcriptionId: { eq: transcriptionId },
          _deleted: { ne: true }
        },
        limit: 1000 // Set high limit to get all invites for this transcription
      }
    }) as GraphQLResponse<ListInvitesResponse>;

    return processInviteResponse(response, transcriptionId);

  } catch (error) {
    console.error('❌ Failed to load invites for transcription:', error);
    
    // If it's a GraphQL error with partial data, try to extract what we can
    if (error && typeof error === 'object' && 'data' in error) {
      console.log('🔄 Attempting to recover partial data from GraphQL error...');
      const errorResponse = error as any;
      
      const recovered = processInviteResponse(errorResponse, transcriptionId);
      console.log(`✅ Recovered ${recovered.length} invites from partial data`);
      return recovered;
    }
    
    // If we can't recover any data, re-throw the error
    throw error;
  }
};

/**
 * Helper function to process invite response data and filter valid records
 */
const processInviteResponse = (response: any, transcriptionId: string): InviteModel[] => {
  // Handle GraphQL errors gracefully - some records might have null values for non-nullable fields
  let invites: InviteData[] = [];
  
  if (response.data?.listInvites?.items) {
    console.log(`📝 Processing ${response.data.listInvites.items.length} raw invite items`);
    
    // Filter out any items that might be problematic due to null required fields
    invites = response.data.listInvites.items.filter((invite: any, index: number) => {
      console.log(`📋 Processing invite ${index}:`, invite);
      
      if (!invite) {
        console.log(`⚠️ Skipping null/undefined invite at index ${index}`);
        return false;
      }
      
      // Check required fields
      const hasRequiredFields = invite.id && 
                               invite.email && 
                               invite.transcriptionId === transcriptionId &&
                               invite.status &&
                               invite.permissionLevel;
      
      if (!hasRequiredFields) {
        console.log(`⚠️ Skipping invite ${index} with missing required fields:`, {
          id: invite.id,
          email: invite.email,
          transcriptionId: invite.transcriptionId,
          expectedTranscriptionId: transcriptionId,
          status: invite.status,
          permissionLevel: invite.permissionLevel,
          fullInvite: invite
        });
        return false;
      }
      
      // The invite is valid for our purposes, even if it has null _version/_lastChangedAt
      console.log(`✅ Valid invite found at index ${index}:`, invite.email, invite.status);
      return true;
    }).map((invite: any) => {
      // Create a clean invite object with defaults for missing metadata fields
      return {
        id: invite.id,
        email: invite.email,
        status: invite.status,
        permissionLevel: invite.permissionLevel,
        expiresAt: invite.expiresAt,
        invitedBy: invite.invitedBy,
        invitedByFriendly: invite.invitedByFriendly,
        createdAt: invite.createdAt,
        acceptedAt: invite.acceptedAt,
        transcriptionId: invite.transcriptionId,
        updatedAt: invite.updatedAt,
        // Provide defaults for problematic fields
        _version: invite._version || 1,
        _deleted: invite._deleted || false,
        _lastChangedAt: invite._lastChangedAt || Date.now(),
      } as InviteData;
    });
  }

  // Log any GraphQL errors but don't fail completely
  if (response.errors && response.errors.length > 0) {
    console.warn('⚠️ GraphQL errors encountered while loading invites (continuing with available data):', response.errors);
  }
  
  console.log(`✅ Processed ${invites.length} valid invites`);
  
  return invites.map((invite: InviteData) => new InviteModel(invite));
};

/**
 * Sends an invite via the API Gateway endpoint (which creates the invite record AND sends email)
 * @param data The invite data to send
 * @returns The API response with messageId
 */
export const sendInvite = async (data: CreateInviteData): Promise<{ messageId: string; inviteId: string }> => {
  try {
    console.log('🔄 Sending invite via API Gateway:', data);

    const response = await post({
      apiName: 'invite',
      path: '/invite',
      options: {
        body: data as any // Type assertion to match AWS Amplify API requirements
      }
    }).response;
    
    const result = await response.body.json() as { 
      success: boolean; 
      messageId?: string; 
      error?: string; 
      email?: string; 
      inviteId?: string; 
    };
    
    if (result && result.success) {
      console.log('✅ Invite sent successfully:', result.messageId);
      return {
        messageId: result.messageId || '',
        inviteId: result.inviteId || ''
      };
    } else {
      // Throw the specific error message from the backend
      const errorMessage = result?.error || 'API returned error';
      console.error('❌ Backend returned error:', errorMessage);
      throw new Error(errorMessage);
    }
  } catch (error: any) {
    console.error('❌ API call failed:', error);
    
    // AWS Amplify wraps HTTP errors differently
    // Check if this is a RestApiError with status and body
    if (error.response?.statusCode) {
      const statusCode = error.response.statusCode;
      console.log(`❌ HTTP ${statusCode} error response`);
      
      // Try to extract error message from response body
      const responseBody = error.response.body;
      if (responseBody) {
        let errorData = null;
        try {
          // Response body might be a string or parsed object
          errorData = typeof responseBody === 'string' ? JSON.parse(responseBody) : responseBody;
        } catch (parseError) {
          console.warn('❌ Could not parse error response body as JSON:', parseError);
        }
        
        // If we successfully parsed and found an error message, use it
        if (errorData && errorData.error) {
          console.error('❌ Backend error message:', errorData.error);
          throw new Error(errorData.error);
        }
      }
    }
    
    // Check for other AWS Amplify error patterns
    if (error.message && error.message !== 'Unknown error') {
      console.error('❌ AWS Amplify error:', error.message);
      throw new Error(error.message);
    }
    
    // Check if error has a more specific error property
    if (error.error && typeof error.error === 'string') {
      console.error('❌ Error property:', error.error);
      throw new Error(error.error);
    }
    
    // For truly unknown errors, throw a helpful message
    console.error('❌ Unknown error structure:', error);
    throw new Error('Failed to send invite. Please try again.');
  }
};

/**
 * Deletes an invite (hard delete)
 * @param inviteId The ID of the invite to delete
 * @returns Success confirmation
 */
export const deleteInvite = async (inviteId: string): Promise<void> => {
  try {
    console.log('🔄 Deleting invite:', inviteId);

    const { data: result } = await getClient().graphql({
      query: deleteInviteMutation,
      variables: { input: { id: inviteId } },
      authMode: 'iam',
    }) as DeleteInviteResponse;

    const deleted = result?.deleteInvite;
    if (!deleted) {
      throw new Error('Failed to delete invite - no data returned');
    }

    console.log('✅ Invite deleted successfully:', deleted.id);
  } catch (error) {
    console.error('❌ Failed to delete invite via API:', error);
    throw error;
  }
}; 