import { generateClient, post } from 'aws-amplify/api';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - GraphQL queries are generated as JS files
import { listInvites } from '../graphql/queries.js';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - GraphQL mutations are generated as JS files
import { deleteInvite as deleteInviteMutation } from '../graphql/mutations.js';

import { InviteModel, type InviteData } from './adt';
import { 
  type GraphQLClient, 
  type GraphQLResponse 
} from '../types/shared';

// Create GraphQL client lazily
let client: GraphQLClient | null = null;
const getClient = (): GraphQLClient => {
  if (!client) {
    client = generateClient() as GraphQLClient;
  }
  return client;
};

// For testing: reset the client
export const __resetClient = () => {
  client = null;
};

export interface CreateInviteData {
  email: string;
  permissionLevel: 'viewer' | 'editor';
  transcriptionId: string;
  transcriptionTitle: string;
  invitedBy: string;
  invitedByFriendly: string;
}

export interface UpdateInviteData {
  id: string;
  status?: string;
  permissionLevel?: 'viewer' | 'editor';
  _version: number;
}

interface ListInvitesResponse {
  listInvites: {
    items: InviteData[];
    nextToken?: string;
  };
}



interface DeleteInviteResponse {
  data: {
    deleteInvite: InviteData;
  };
}

interface GraphQLError {
  message: string;
  path?: (string | number)[];
  locations?: { line: number; column: number }[];
  extensions?: Record<string, unknown>;
}

interface GraphQLListResponse {
  data?: {
    listInvites?: {
      items: (InviteData | null)[];
      nextToken?: string;
    };
  };
  errors?: GraphQLError[];
}

// AWS Amplify error types
interface AmplifyHttpResponse {
  statusCode: number;
  body: string | Record<string, unknown>;
}

interface AmplifyApiError {
  message?: string;
  response?: AmplifyHttpResponse;
  error?: string;
}



/**
 * Loads all invites for a specific transcription
 * 
 * NOTE: This should ideally use an 'invitesByTranscription' index query 
 * (generated from @index(name: "ByTranscription", queryField: "invitesByTranscription"))
 * but that query is not being generated by Amplify. Using listInvites with 
 * filter as a workaround, consistent with regionService.ts approach.
 * 
 * @param transcriptionId The ID of the transcription
 * @returns Array of InviteModel instances
 */
export const loadInvitesForTranscription = async (transcriptionId: string): Promise<InviteModel[]> => {
  try {
    console.debug(`🔍 Loading invites for transcription: ${transcriptionId}`);
    
    const response = await getClient().graphql({
      query: listInvites,
      variables: {
        filter: {
          transcriptionId: { eq: transcriptionId },
          _deleted: { ne: true }
        },
        limit: 1000 // Set high limit to get all invites for this transcription
      }
    }) as GraphQLResponse<ListInvitesResponse>;

    return processInviteResponse(response, transcriptionId);

  } catch (error) {
    console.error('❌ Failed to load invites for transcription:', error);
    throw error;
  }
};

/**
 * Helper function to process invite response data and filter valid records
 */
const processInviteResponse = (response: GraphQLListResponse, transcriptionId: string): InviteModel[] => {
  // Handle GraphQL errors gracefully - some records might have null values for non-nullable fields
  let invites: InviteData[] = [];
  
  if (response.data?.listInvites?.items) {
    console.debug(`📝 Processing ${response.data.listInvites.items.length} raw invite items`);
    
    // Filter out any items that might be problematic due to null required fields
    invites = response.data.listInvites.items.filter((invite: InviteData | null, index: number): invite is InviteData => {
      console.debug(`📋 Processing invite ${index}:`, invite);
      
      if (!invite) {
        console.debug(`⚠️ Skipping null/undefined invite at index ${index}`);
        return false;
      }
      
      // Check required fields
      const hasRequiredFields = invite.id && 
                               invite.email && 
                               invite.transcriptionId === transcriptionId &&
                               invite.status &&
                               invite.permissionLevel;
      
      if (!hasRequiredFields) {
        console.debug(`⚠️ Skipping invite ${index} with missing required fields:`, {
          id: invite.id,
          email: invite.email,
          transcriptionId: invite.transcriptionId,
          expectedTranscriptionId: transcriptionId,
          status: invite.status,
          permissionLevel: invite.permissionLevel,
          fullInvite: invite
        });
        return false;
      }
      
      // The invite is valid for our purposes, even if it has null _version/_lastChangedAt
      console.debug(`✅ Valid invite found at index ${index}:`, invite.email, invite.status);
      return true;
    }).map((invite: InviteData) => {
      // Create a clean invite object with defaults for missing metadata fields
      return {
        id: invite.id,
        email: invite.email,
        status: invite.status,
        permissionLevel: invite.permissionLevel,
        expiresAt: invite.expiresAt,
        invitedBy: invite.invitedBy,
        invitedByFriendly: invite.invitedByFriendly,
        createdAt: invite.createdAt,
        acceptedAt: invite.acceptedAt,
        transcriptionId: invite.transcriptionId,
        transcriptionTitle: invite.transcriptionTitle || 'Unknown Transcription',
        updatedAt: invite.updatedAt,
      };
    });
  }

  // Log any GraphQL errors but don't fail completely
  if (response.errors && response.errors.length > 0) {
    console.warn('⚠️ GraphQL errors encountered while loading invites (continuing with available data):', response.errors);
  }
  
  console.debug(`✅ Processed ${invites.length} valid invites`);
  
  return invites.map((invite: InviteData) => new InviteModel(invite));
};

/**
 * Sends an invite via the API Gateway endpoint (which creates the invite record AND sends email)
 * @param data The invite data to send
 * @returns The API response with messageId
 */
export const sendInvite = async (data: CreateInviteData): Promise<{ messageId: string; inviteId: string }> => {
  try {
    console.debug('🔄 Sending invite via API Gateway:', data);

    const response = await post({
      apiName: 'invite',
      path: '/invite',
      options: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        body: data as any // AWS Amplify API requires this type assertion
      }
    }).response;
    
    const result = await response.body.json() as { 
      success: boolean; 
      messageId?: string; 
      error?: string; 
      email?: string; 
      inviteId?: string; 
    };
    
    if (result && result.success) {
      console.info('✅ Invite sent successfully:', result.messageId);
      return {
        messageId: result.messageId || '',
        inviteId: result.inviteId || ''
      };
    } else {
      // Throw the specific error message from the backend
      const errorMessage = result?.error || 'API returned error';
      console.error('❌ Backend returned error:', errorMessage);
      throw new Error(errorMessage);
    }
  } catch (error: unknown) {
    console.error('❌ API call failed:', error);
    
    const apiError = error as AmplifyApiError;
    
    // AWS Amplify wraps HTTP errors differently
    // Check if this is a RestApiError with status and body
    if (apiError.response?.statusCode) {
      // Try to extract error message from response body
      const responseBody = apiError.response.body;
      if (responseBody) {
        let errorData = null;
        try {
          // Response body might be a string or parsed object
          errorData = typeof responseBody === 'string' ? JSON.parse(responseBody) : responseBody;
        } catch (parseError) {
          console.warn('❌ Could not parse error response body as JSON:', parseError);
        }
        
        // If we successfully parsed and found an error message, use it
        if (errorData && errorData.error) {
          console.error('❌ Backend error message:', errorData.error);
          throw new Error(errorData.error);
        }
      }
    }
    
    // Check for other AWS Amplify error patterns
    if (apiError.message && apiError.message !== 'Unknown error') {
      console.error('❌ AWS Amplify error:', apiError.message);
      throw new Error(apiError.message);
    }
    
    // Check if error has a more specific error property
    if (apiError.error && typeof apiError.error === 'string') {
      console.error('❌ Error property:', apiError.error);
      throw new Error(apiError.error);
    }
    
    // For truly unknown errors, throw a helpful message
    console.error('❌ Unknown error structure:', error);
    throw new Error('Failed to send invite. Please try again.');
  }
};

/**
 * Revokes an invitation (deletes invite and removes user from transcription ACLs)
 * @param inviteId The ID of the invite to revoke
 * @param requestorEmail Email of the person requesting the revocation
 * @returns Success confirmation with details
 */
export const revokeInvite = async (inviteId: string, requestorUserId: string): Promise<{
  message: string;
  inviteId: string;
  email: string;
  transcriptionId: string;
  wasAccepted: boolean;
  permissionLevel: 'viewer' | 'editor';
}> => {
  try {
    console.debug('🔄 Revoking invite:', { inviteId, requestorUserId });

    const response = await post({
      apiName: 'invite',
      path: '/invite/revoke',
      options: {
        body: {
          inviteId,
          requestorUserId
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
        } as any // AWS Amplify API requires this type assertion
      }
    }).response;

    const result = (await response.body.json()) as unknown as {
      success: boolean;
      message?: string;
      inviteId?: string;
      email?: string;
      transcriptionId?: string;
      wasAccepted?: boolean;
      permissionLevel?: 'viewer' | 'editor';
      error?: string;
    };

    if (!result.success) {
      throw new Error(result.error || 'Failed to revoke invite');
    }

    console.info('✅ Invite revoked successfully:', result);
    return {
      message: result.message || 'Invitation revoked successfully',
      inviteId: result.inviteId!,
      email: result.email!,
      transcriptionId: result.transcriptionId!,
      wasAccepted: result.wasAccepted!,
      permissionLevel: result.permissionLevel!
    };
  } catch (error: unknown) {
    console.error('❌ Revoke invite API call failed:', error);

    const apiError = error as AmplifyApiError;

    // Try to parse API Gateway error response
    try {
      if (apiError.response?.statusCode === 400) {
        const responseBody = apiError.response.body;
        if (typeof responseBody === 'string') {
          const errorResponse = JSON.parse(responseBody);
          throw new Error(errorResponse.error || 'Bad request');
        } else if (responseBody && typeof responseBody === 'object') {
          throw new Error((responseBody as { error?: string }).error || 'Bad request');
        }
      }
    } catch {
      // If we can't parse the error response, fall through to generic handling
    }

    throw new Error(apiError.message || 'Failed to revoke invite. Please try again.');
  }
};

/**
 * Deletes an invite (hard delete) - Legacy function, use revokeInvite instead
 * @param inviteId The ID of the invite to delete
 * @returns Success confirmation
 */
export const deleteInvite = async (inviteId: string): Promise<void> => {
  try {
    console.debug('🔄 Deleting invite:', inviteId);

    const { data: result } = await getClient().graphql({
      query: deleteInviteMutation,
      variables: { input: { id: inviteId } },
      authMode: 'userPool',
    }) as DeleteInviteResponse;

    const deleted = result?.deleteInvite;
    if (!deleted) {
      throw new Error('Failed to delete invite - no data returned');
    }

    console.info('✅ Invite deleted successfully:', deleted.id);
  } catch (error) {
    console.error('❌ Failed to delete invite via API:', error);
    throw error;
  }
};

export interface GetMyInvitesRequest {
  userEmail: string;
  transcriptionId?: string;
  inviteId?: string;
  includeTranscriptionData?: boolean;
  sinceTimestamp?: string; // For incremental sync
}

export interface InviteWithValidation {
  invite: {
    id: string;
    email: string;
    status: string;
    permissionLevel: 'viewer' | 'editor';
    expiresAt: string;
    invitedBy: string;
    invitedByFriendly: string;
    createdAt: string;
    acceptedAt?: string;
    transcriptionId: string;
    transcriptionTitle: string;
    updatedAt?: string;
  };
  validation: {
    isValid: boolean;
    isExpired: boolean;
    isPending: boolean;
    isAccepted: boolean;
    canAccept: boolean;
  };
  transcription?: {
    id: string;
    title: string;
    author: string;
    authorFriendly: string;
    type: string;
    length: number;
    coverage: number;
    issueCount: number;
    regionCount: number;
    commentCount: number;
    isPrivate: boolean;
    dateLastUpdated: string;
    userLastUpdated: string;
    createdAt: string;
    updatedAt: string;
  };
}

export interface GetMyInvitesResponse {
  invites: InviteWithValidation[];
  total: number;
  filters: {
    userEmail: string;
    transcriptionId: string | null;
    inviteId: string | null;
  };
}

/**
 * Gets user's invites via the backend Lambda (with optional filtering)
 * @param request Request parameters for getting invites
 * @returns Array of invites with validation info
 */
export const getMyInvites = async (request: GetMyInvitesRequest): Promise<GetMyInvitesResponse> => {
  try {
    console.debug('🔍 Loading my invites:', request);

    const response = await post({
      apiName: 'invite',
      path: '/invite/mine',
      options: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        body: request as any // Type assertion to match AWS Amplify API requirements
      }
    }).response;

    const result = (await response.body.json()) as unknown as {
      success: boolean;
      invites?: InviteWithValidation[];
      total?: number;
      filters?: GetMyInvitesResponse['filters'];
      error?: string;
    };

    if (result && result.success) {
      console.debug('✅ My invites loaded successfully:', result);
      return {
        invites: result.invites || [],
        total: result.total || 0,
        filters: result.filters || { userEmail: request.userEmail, transcriptionId: null, inviteId: null }
      };
    } else {
      // Throw the specific error message from the backend
      const errorMessage = result?.error || 'API returned error';
      console.error('❌ Backend returned error:', errorMessage);
      throw new Error(errorMessage);
    }
  } catch (error: unknown) {
    console.error('❌ Get my invites API call failed:', error);

    const apiError = error as AmplifyApiError;

    // AWS Amplify wraps HTTP errors differently
    // Check if this is a RestApiError with status and body
    if (apiError.response?.statusCode) {
      // Try to extract error message from response body
      const responseBody = apiError.response.body;
      if (responseBody) {
        let errorData = null;
        try {
          // Response body might be a string or parsed object
          errorData = typeof responseBody === 'string' ? JSON.parse(responseBody) : responseBody;
        } catch (parseError) {
          console.warn('❌ Could not parse error response body as JSON:', parseError);
        }

        // If we successfully parsed and found an error message, use it
        if (errorData && errorData.error) {
          console.error('❌ Backend error message:', errorData.error);
          throw new Error(errorData.error);
        }
      }
    }

    // Check for other AWS Amplify error patterns
    if (apiError.message && apiError.message !== 'Unknown error') {
      console.error('❌ AWS Amplify error:', apiError.message);
      throw new Error(apiError.message);
    }

    // Check if error has a more specific error property
    if (apiError.error && typeof apiError.error === 'string') {
      console.error('❌ Error property:', apiError.error);
      throw new Error(apiError.error);
    }

    // For truly unknown errors, throw a helpful message
    console.error('❌ Unknown error structure:', error);
    throw new Error('Failed to load invites. Please try again.');
  }
};

/**
 * Gets a single invite by ID via the backend Lambda
 * @param inviteId The ID of the invite to retrieve
 * @param userEmail The user's email for validation
 * @returns InviteModel instance with validation info or null if not found
 */
export const getInviteById = async (inviteId: string, userEmail: string): Promise<{ invite: InviteModel; validation: InviteWithValidation['validation'] } | null> => {
  try {
    console.debug('🔍 Loading invite by ID:', inviteId);

    const result = await getMyInvites({
      userEmail,
      inviteId
    });

    const inviteWithValidation = result.invites[0];
    
    if (!inviteWithValidation) {
      console.debug('❌ Invite not found:', inviteId);
      return null;
    }

    console.debug('✅ Invite loaded successfully:', inviteId);
    return {
      invite: new InviteModel(inviteWithValidation.invite),
      validation: inviteWithValidation.validation
    };
  } catch (error) {
    console.error('❌ Failed to load invite by ID:', error);
    throw error;
  }
};

export interface AcceptInviteData {
  inviteId: string;
  userEmail: string;
  userId: string;
}

export interface AcceptInviteResult {
  message: string;
  invite: {
    inviteId: string;
    email: string;
    permissionLevel: 'viewer' | 'editor';
    transcriptionId: string;
    invitedBy: string;
    invitedByFriendly: string;
    acceptedAt: string;
    status: string;
  };
}

/**
 * Accepts an invite by calling the backend Lambda
 * @param data Accept invite request data
 * @returns Success confirmation with updated invite details
 */
export const acceptInvite = async (data: AcceptInviteData): Promise<AcceptInviteResult> => {
  try {
    console.debug('🔄 Accepting invite:', { inviteId: data.inviteId, userEmail: data.userEmail });

    const response = await post({
      apiName: 'invite',
      path: '/invite/accept',
      options: {
        body: {
          inviteId: data.inviteId,
          userEmail: data.userEmail,
          userId: data.userId
        }
      }
    }).response;

    const result = await response.body.json() as {
      success: boolean;
      message?: string;
      invite?: AcceptInviteResult['invite'];
      error?: string;
    };

    if (result && result.success) {
      console.info('✅ Invite accepted successfully:', result);
      return {
        message: result.message || 'Invitation accepted successfully',
        invite: result.invite!
      };
    } else {
      // Throw the specific error message from the backend
      const errorMessage = result?.error || 'API returned error';
      console.error('❌ Backend returned error:', errorMessage);
      throw new Error(errorMessage);
    }
  } catch (error: unknown) {
    console.error('❌ Accept invite API call failed:', error);

    const apiError = error as AmplifyApiError;

    // AWS Amplify wraps HTTP errors differently
    // Check if this is a RestApiError with status and body
    if (apiError.response?.statusCode) {
      // Try to extract error message from response body
      const responseBody = apiError.response.body;
      if (responseBody) {
        let errorData = null;
        try {
          // Response body might be a string or parsed object
          errorData = typeof responseBody === 'string' ? JSON.parse(responseBody) : responseBody;
        } catch (parseError) {
          console.warn('❌ Could not parse error response body as JSON:', parseError);
        }

        // If we successfully parsed and found an error message, use it
        if (errorData && errorData.error) {
          console.error('❌ Backend error message:', errorData.error);
          throw new Error(errorData.error);
        }
      }
    }

    // Check for other AWS Amplify error patterns
    if (apiError.message && apiError.message !== 'Unknown error') {
      console.error('❌ AWS Amplify error:', apiError.message);
      throw new Error(apiError.message);
    }

    // Check if error has a more specific error property
    if (apiError.error && typeof apiError.error === 'string') {
      console.error('❌ Error property:', apiError.error);
      throw new Error(apiError.error);
    }

    // For truly unknown errors, throw a helpful message
    console.error('❌ Unknown error structure:', error);
    throw new Error('Failed to accept invite. Please try again.');
  }
}; 