# version: 2
# jobs:
#   run_tests:
#     docker:
#       - image: circleci/node:8.16.0-stretch
#     steps:
#       - checkout
#       - run:
#           name: Install kiyânaw deps
#           command: npm install
#       - run:
#           name: Run mocha tests
#           command: npm run test

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - run_tests
