version: 2.1
npm_cache_key: &npm_cache_key node-v12-dependency-cache-{{ checksum "package-lock.json" }}
orbs:
  ghostinspector: ghostinspector/test-runner@1.0.2
jobs:
  test-browser:
    docker:
      - image: circleci/node:12-buster-browsers
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache_key
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
      - run:
          name: Run Karma
          command: npm run karma
  integration-tests:
    executor: docker
    steps:
      - ghostinspector/execute-suite:
          id: 59f33e968ba4c50f26eab519
          wait: true
workflows:
  build_and_test:
    jobs:
      - test-browser
      - integration-tests
