version: 2.1

npm_cache_key: &npm_cache_key node-v12-dependency-cache-{{ checksum "package-lock.json" }}

orbs:
  ghostinspector: ghostinspector/test-runner@1.0.2
  slack: circleci/slack@2.2.0

references:
  notifications: &notifications
    include_project_field: true
    include_job_number_field: true
    include_visit_job_action: true

jobs:
  test-browser:
    docker:
      - image: cimg/node:12-buster-browsers
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache_key
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
      - run:
          name: Run Karma
          command: npm run karma
      - slack/status:
          <<: *notifications
          fail_only: 'true'

  integration-tests:
    docker:
      - image: cimg/node:lts
    steps:
      - ghostinspector/execute-suite:
          id: 59f33e968ba4c50f26eab519
          wait: true
      - slack/status:
          <<: *notifications
          fail_only: 'true'

workflows:
  build_and_test:
    jobs:
      - test-browser
      - integration-tests
