name: Test Workflow

on:
  push:
    branches: [ "2023-realtime-changes" ]
  pull_request:
    branches: [ "2023-realtime-changes" ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:karma
    - run: npm run test:unit
