name: NPM test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: execute Ghost Inspector suite
        uses: docker://ghostinspector/cli
        with:
          args: suite execute ${{ secrets.GI_SUITE }} \
            --apiKey ${{ secrets.GI_API_KEY }} \
            --startUrl https://google.com \
            --errorOnFail
